# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: A Comparison between Threads, Fibers and Coroutines for Developing Concurrent Software
email: senne.bergmans@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site contains the additional information and source code mentioned in the paper "A Comparison between Threads, Fibers and Coroutines for Developing Concurrent Software".
  The site contains the full code examples that were mentioned in the paper.
  It provides all tests that were conducted so they can be checked and retested.
  It explains certain new topics that where researched for the paper but ended up not fitting inside of the paper due to the ten page size limit.
baseurl: "/AComparisonBetweenThreadsFibersAndCoroutines" # the subpath of your site, e.g. /blog
url: "https://sennebergmans.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SenneBergmans

# Build settings
theme: minima
plugins:
  - jekyll-feed
collections:
  bachelor_thesis_pages:
    output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
